In [21]:
import pandas as pd
import numpy as np

In [22]:
from tmdbv3api import TMDb
from tmdbv3api import Movie
import json
import requests

tmdb = TMDb()
tmdb_movie = Movie()
tmdb.api_key = '4606882be56455abf5485c21adf285fb'

Extracting movie data from Wikipedia - 2021

In [23]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2021"

dfs = pd.read_html(link, header=0)

if len(dfs) >= 6:
    df1 = dfs[2]
    df2 = dfs[3]
    df3 = dfs[4]
    df4 = dfs[5]

    # Combine DataFrames vertically
    df = pd.concat([df1, df2, df3, df4], ignore_index=True)

    # Define the get_genre function
    def get_genre(x):
        genres = []
        result = tmdb_movie.search(x)
        if len(result) > 0:
            movie_id = result[0].id
            response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id, tmdb.api_key))
            data_json = response.json()
            if data_json['genres']:
                genre_str = " " 
                for i in range(0, len(data_json['genres'])):
                    genres.append(data_json['genres'][i]['name'])
                return genre_str.join(genres)
        return np.NaN

    # Apply the get_genre function to the 'Title' column
    df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))

    # Print the resulting DataFrame
    print(df)
else:
    print("Not enough DataFrames found on the page.")

             Opening  Opening.1                   Title
0      J A N U A R Y        1.0     Shadow in the Cloud  \
1      J A N U A R Y       13.0         The White Tiger
2      J A N U A R Y       14.0             Locked Down
3      J A N U A R Y       15.0                 The Dig
4      J A N U A R Y       15.0        Outside the Wire
..               ...        ...                     ...
356  D E C E M B E R       25.0  The Tragedy of Macbeth
357  D E C E M B E R       25.0    A Journal for Jordan
358  D E C E M B E R       25.0       American Underdog
359  D E C E M B E R       26.0                 Memoria
360  D E C E M B E R        NaN                     NaN

                                    Production company
0                               Vertical Entertainment  \
1                                Netflix / Noruz Films
2                      HBO Max / Warner Bros. Pictures
3                          Netflix / Clerkenwell Films
4                                              Netflix
..                                                 ...
356                        Apple TV+ / A24 / IAC Films
357  Columbia Pictures / Escape Artists / Bron Studios
358                                          Lionsgate
359                                               Neon
360                                                NaN

                                         Cast and crew
0    Roseanne Liang (director/screenplay); Max Land...  \
1    Ramin Bahrani (director/screenplay); Adarsh Go...
2    Doug Liman (director); Steven Knight (screenpl...
3    Simon Stone (director); Moira Buffini (screenp...
4    Mikael Håfström (director); Rob Yescombe, Rowa...
..                                                 ...
356  Joel Coen (director/screenplay); Denzel Washin...
357  Denzel Washington (director); Virgil Williams ...
358  Erwin brothers (directors); Jon Erwin, David A...
359  Apichatpong Weerasethakul (director/acreenplay...
360                                                NaN

    .mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.
0                                                  [2]                           \
1                                                  NaN
2                                                  [3]
3                                                  [4]
4                                                  [5]
..                                                 ...
356                                                NaN
357                                                NaN
358                                                NaN
359                                                NaN
360                                                NaN

      Ref.                           genres
0      NaN                Horror Action War
1      NaN                            Drama
2      NaN               Comedy Crime Drama
3      NaN                    Drama History
4      NaN  Thriller Action Science Fiction
..     ...                              ...
356  [273]                        Drama War
357  [274]                    Drama Romance
358  [275]                            Drama
359  [276]                            Drama
360    NaN                            Drama

[361 rows x 8 columns]

In [24]:
df

,Opening,Opening.1,Title,Production company,Cast and crew,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Ref.,genres
0,J A N U A R Y,1.0,Shadow in the Cloud,Vertical Entertainment,Roseanne Liang (director/screenplay); Max Land...,[2],NaN,Horror Action War
1,J A N U A R Y,13.0,The White Tiger,Netflix / Noruz Films,Ramin Bahrani (director/screenplay); Adarsh Go...,NaN,NaN,Drama
2,J A N U A R Y,14.0,Locked Down,HBO Max / Warner Bros. Pictures,Doug Liman (director); Steven Knight (screenpl...,[3],NaN,Comedy Crime Drama
3,J A N U A R Y,15.0,The Dig,Netflix / Clerkenwell Films,Simon Stone (director); Moira Buffini (screenp...,[4],NaN,Drama History
4,J A N U A R Y,15.0,Outside the Wire,Netflix,"Mikael Håfström (director); Rob Yescombe, Rowa...",[5],NaN,Thriller Action Science Fiction
...,...,...,...,...,...,...,...,...
356,D E C E M B E R,25.0,The Tragedy of Macbeth,Apple TV+ / A24 / IAC Films,Joel Coen (director/screenplay); Denzel Washin...,NaN,[273],Drama War
357,D E C E M B E R,25.0,A Journal for Jordan,Columbia Pictures / Escape Artists / Bron Studios,Denzel Washington (director); Virgil Williams ...,NaN,[274],Drama Romance
358,D E C E M B E R,25.0,American Underdog,Lionsgate,"Erwin brothers (directors); Jon Erwin, David A...",NaN,[275],Drama
359,D E C E M B E R,26.0,Memoria,Neon,Apichatpong Weerasethakul (director/acreenplay...,NaN,[276],Drama
360,D E C E M B E R,NaN,NaN,NaN,NaN,NaN,NaN,Drama

In [25]:
df_2021 = df[['Title','Cast and crew','genres']]
df_2021

,Title,Cast and crew,genres
0,Shadow in the Cloud,Roseanne Liang (director/screenplay); Max Land...,Horror Action War
1,The White Tiger,Ramin Bahrani (director/screenplay); Adarsh Go...,Drama
2,Locked Down,Doug Liman (director); Steven Knight (screenpl...,Comedy Crime Drama
3,The Dig,Simon Stone (director); Moira Buffini (screenp...,Drama History
4,Outside the Wire,"Mikael Håfström (director); Rob Yescombe, Rowa...",Thriller Action Science Fiction
...,...,...,...
356,The Tragedy of Macbeth,Joel Coen (director/screenplay); Denzel Washin...,Drama War
357,A Journal for Jordan,Denzel Washington (director); Virgil Williams ...,Drama Romance
358,American Underdog,"Erwin brothers (directors); Jon Erwin, David A...",Drama
359,Memoria,Apichatpong Weerasethakul (director/acreenplay...,Drama
360,NaN,NaN,Drama

In [26]:
def get_director(x):
    if isinstance(x, str):
        if " (director)" in x:
            return x.split(" (director)")[0]
        elif " (directors)" in x:
            return x.split(" (directors)")[0]
        elif " (director/screenplay)" in x:
            return x.split(" (director/screenplay)")[0]
    return np.NaN

df_2021['director_name'] = df_2021['Cast and crew'].map(lambda x: get_director(x))

C:\Users\user\AppData\Local\Temp\ipykernel_9672\3171294844.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['director_name'] = df_2021['Cast and crew'].map(lambda x: get_director(x))

In [27]:
def get_actor1(x):
    if isinstance(x, str):
        split_values = x.split("screenplay); ")
        if len(split_values) > 1:
            return split_values[-1].split(", ")[0]
    return np.NaN

df_2021['actor_1_name'] = df_2021['Cast and crew'].map(lambda x: get_actor1(x))

def get_actor2(x):
    if isinstance(x, str):
        split_values = x.split("screenplay); ")
        if len(split_values) > 1 and len(split_values[-1].split(", ")) >= 2:
            return split_values[-1].split(", ")[1]
    return np.NaN

df_2021['actor_2_name'] = df_2021['Cast and crew'].map(lambda x: get_actor2(x))

def get_actor3(x):
    if isinstance(x, str):
        split_values = x.split("screenplay); ")
        if len(split_values) > 1 and len(split_values[-1].split(", ")) >= 3:
            return split_values[-1].split(", ")[2]
    return np.NaN

df_2021['actor_3_name'] = df_2021['Cast and crew'].map(lambda x: get_actor3(x))

C:\Users\user\AppData\Local\Temp\ipykernel_9672\2537080157.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['actor_1_name'] = df_2021['Cast and crew'].map(lambda x: get_actor1(x))
C:\Users\user\AppData\Local\Temp\ipykernel_9672\2537080157.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['actor_2_name'] = df_2021['Cast and crew'].map(lambda x: get_actor2(x))
C:\Users\user\AppData\Local\Temp\ipykernel_9672\2537080157.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2021['actor_3_name'] = df_2021['Cast and crew'].map(lambda x: get_actor3(x))

In [28]:
df_2021

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,Shadow in the Cloud,Roseanne Liang (director/screenplay); Max Land...,Horror Action War,Roseanne Liang,Chloë Grace Moretz,Taylor John Smith,Beulah Koale
1,The White Tiger,Ramin Bahrani (director/screenplay); Adarsh Go...,Drama,Ramin Bahrani,Adarsh Gourav,Rajkummar Rao,Priyanka Chopra Jonas
2,Locked Down,Doug Liman (director); Steven Knight (screenpl...,Comedy Crime Drama,Doug Liman,Anne Hathaway,Chiwetel Ejiofor,Stephen Merchant
3,The Dig,Simon Stone (director); Moira Buffini (screenp...,Drama History,Simon Stone,Carey Mulligan,Ralph Fiennes,Lily James
4,Outside the Wire,"Mikael Håfström (director); Rob Yescombe, Rowa...",Thriller Action Science Fiction,Mikael Håfström,Anthony Mackie,Damson Idris,Emily Beecham
...,...,...,...,...,...,...,...
356,The Tragedy of Macbeth,Joel Coen (director/screenplay); Denzel Washin...,Drama War,Joel Coen,Denzel Washington,Frances McDormand,Bertie Carvel
357,A Journal for Jordan,Denzel Washington (director); Virgil Williams ...,Drama Romance,Denzel Washington,Michael B. Jordan,Chanté Adams,Jalon Christian
358,American Underdog,"Erwin brothers (directors); Jon Erwin, David A...",Drama,Erwin brothers,Zachary Levi,Anna Paquin,Dennis Quaid
359,Memoria,Apichatpong Weerasethakul (director/acreenplay...,Drama,NaN,NaN,NaN,NaN
360,NaN,NaN,Drama,NaN,NaN,NaN,NaN

In [29]:
df_2021 = df_2021.rename(columns={'Title':'movie_title'})

In [30]:
new_df21 = df_2021.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

new_df21

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Roseanne Liang,Chloë Grace Moretz,Taylor John Smith,Beulah Koale,Horror Action War,Shadow in the Cloud
1,Ramin Bahrani,Adarsh Gourav,Rajkummar Rao,Priyanka Chopra Jonas,Drama,The White Tiger
2,Doug Liman,Anne Hathaway,Chiwetel Ejiofor,Stephen Merchant,Comedy Crime Drama,Locked Down
3,Simon Stone,Carey Mulligan,Ralph Fiennes,Lily James,Drama History,The Dig
4,Mikael Håfström,Anthony Mackie,Damson Idris,Emily Beecham,Thriller Action Science Fiction,Outside the Wire
...,...,...,...,...,...,...
356,Joel Coen,Denzel Washington,Frances McDormand,Bertie Carvel,Drama War,The Tragedy of Macbeth
357,Denzel Washington,Michael B. Jordan,Chanté Adams,Jalon Christian,Drama Romance,A Journal for Jordan
358,Erwin brothers,Zachary Levi,Anna Paquin,Dennis Quaid,Drama,American Underdog
359,NaN,NaN,NaN,NaN,Drama,Memoria
360,NaN,NaN,NaN,NaN,Drama,NaN

In [34]:
# Fill NaN values with 'unknown'

new_df21['actor_2_name'] = new_df21['actor_2_name'].replace(np.nan, 'unknown')
new_df21['actor_3_name'] = new_df21['actor_3_name'].replace(np.nan, 'unknown')

new_df21['movie_title'] = new_df21['movie_title'].str.lower()

new_df21['comb'] = new_df21['actor_1_name'] + ' ' + new_df21['actor_2_name'] + ' '+ new_df21['actor_3_name'] + ' '+ new_df21['director_name'] +' ' + new_df21['genres']

new_df21

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Roseanne Liang,Chloë Grace Moretz,Taylor John Smith,Beulah Koale,Horror Action War,shadow in the cloud,Chloë Grace Moretz Taylor John Smith Beulah Ko...
1,Ramin Bahrani,Adarsh Gourav,Rajkummar Rao,Priyanka Chopra Jonas,Drama,the white tiger,Adarsh Gourav Rajkummar Rao Priyanka Chopra Jo...
2,Doug Liman,Anne Hathaway,Chiwetel Ejiofor,Stephen Merchant,Comedy Crime Drama,locked down,Anne Hathaway Chiwetel Ejiofor Stephen Merchan...
3,Simon Stone,Carey Mulligan,Ralph Fiennes,Lily James,Drama History,the dig,Carey Mulligan Ralph Fiennes Lily James Simon ...
4,Mikael Håfström,Anthony Mackie,Damson Idris,Emily Beecham,Thriller Action Science Fiction,outside the wire,Anthony Mackie Damson Idris Emily Beecham Mika...
...,...,...,...,...,...,...,...
356,Joel Coen,Denzel Washington,Frances McDormand,Bertie Carvel,Drama War,the tragedy of macbeth,Denzel Washington Frances McDormand Bertie Car...
357,Denzel Washington,Michael B. Jordan,Chanté Adams,Jalon Christian,Drama Romance,a journal for jordan,Michael B. Jordan Chanté Adams Jalon Christian...
358,Erwin brothers,Zachary Levi,Anna Paquin,Dennis Quaid,Drama,american underdog,Zachary Levi Anna Paquin Dennis Quaid Erwin br...
359,NaN,NaN,unknown,unknown,Drama,memoria,NaN
360,NaN,NaN,unknown,unknown,Drama,NaN,NaN

In [36]:
new_df21.isna().sum()

director_name     7
actor_1_name     21
actor_2_name      0
actor_3_name      0
genres            1
movie_title       1
comb             25
dtype: int64

In [38]:
# drop null valued rows
new_df21 = new_df21.dropna(how='any')
new_df21.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [39]:
new_df21

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Roseanne Liang,Chloë Grace Moretz,Taylor John Smith,Beulah Koale,Horror Action War,shadow in the cloud,Chloë Grace Moretz Taylor John Smith Beulah Ko...
1,Ramin Bahrani,Adarsh Gourav,Rajkummar Rao,Priyanka Chopra Jonas,Drama,the white tiger,Adarsh Gourav Rajkummar Rao Priyanka Chopra Jo...
2,Doug Liman,Anne Hathaway,Chiwetel Ejiofor,Stephen Merchant,Comedy Crime Drama,locked down,Anne Hathaway Chiwetel Ejiofor Stephen Merchan...
3,Simon Stone,Carey Mulligan,Ralph Fiennes,Lily James,Drama History,the dig,Carey Mulligan Ralph Fiennes Lily James Simon ...
4,Mikael Håfström,Anthony Mackie,Damson Idris,Emily Beecham,Thriller Action Science Fiction,outside the wire,Anthony Mackie Damson Idris Emily Beecham Mika...
...,...,...,...,...,...,...,...
354,Lana Wachowski,Keanu Reeves,Carrie-Anne Moss,Yahya Abdul-Mateen II,Science Fiction Action Adventure,the matrix resurrections,Keanu Reeves Carrie-Anne Moss Yahya Abdul-Mate...
355,Matthew Vaughn,Ralph Fiennes,Gemma Arterton,Rhys Ifans,Action Adventure Thriller,the king's man,Ralph Fiennes Gemma Arterton Rhys Ifans Matthe...
356,Joel Coen,Denzel Washington,Frances McDormand,Bertie Carvel,Drama War,the tragedy of macbeth,Denzel Washington Frances McDormand Bertie Car...
357,Denzel Washington,Michael B. Jordan,Chanté Adams,Jalon Christian,Drama Romance,a journal for jordan,Michael B. Jordan Chanté Adams Jalon Christian...
358,Erwin brothers,Zachary Levi,Anna Paquin,Dennis Quaid,Drama,american underdog,Zachary Levi Anna Paquin Dennis Quaid Erwin br...

In [42]:
#  convert to csv file
new_df21.to_csv('new_data2021.csv',index=False)